### ISSUE TITLE
Invalid Link to Course

### ISSUE THREAD

**Issue by elauser** [andkret/Cookbook#102]
Building Cloud Services with the Java Spring Framework (Coursera) Link does not work anymore

**Comment by kakaru1331** [comment]
https://github.com/andkret/Cookbook/blob/master/sections/09-BooksAndCourses.md#online-courses

they have all broken

**Comment by kelvins** [comment]
There is a Github action that can be used to check for broken links:
https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by baky0905** [comment]
@kelvins thanks for linking me to this checker, I will test it asap. It seems to have more stars than the one I stumbled upon, which was https://github.com/lycheeverse/lychee-action

**Comment by baky0905** [comment]
@kelvins I have decided to test out https://github.com/lycheeverse/lychee-action, seems ok so far, I coupled it with the issue creation out of the report (https://github.com/andkret/Cookbook/issues/116) - pleas do comment if you think this is a way to go, since I haven't directly used them before.  If you agree the lychee-action will do the job in helping to identify the broken links on a once a week basis, I will close this issue. 👍 or 👎  😃

**Comment by baky0905** [comment]
@elauser, @kakaru1331 thanks! Links are now fixed - #117
